services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # when using Pi-hole as your DHCP server
      - "67:67/udp"
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - ${DOCKERCONFDIR}/pihole/etc/pihole:/etc/pihole
      - ${DOCKERCONFDIR}/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    network_mode: host
    privileged: true
    volumes:
      - ${DOCKERCONFDIR}/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyACM0
    environment:
      - TZ=${TZ}

